
Ext.define('App.model.transactions.marketing.Registration_unit_ci', {
	extend: 'Ext.data.Model',
    fields :[
        {name:'co_id', type:'string'},
        {name:'doc_id', type:'string'},
        {name:'doc_date', type:'string'},
        {name:'registration_id', type:'integer'},
        {name:'seq_id', type:'integer'},
        {name:'unit_building_id', type:'string'},
        {name:'unit_building_name', type:'string'},
        {name:'building_id', type:'string'},
        {name:'building_name', type:'string'},
        {name:'project_id', type:'string'},
        {name:'project_name', type:'string'},
        {name:'facing_id', type:'string'},
        {name:'facing_name', type:'string'},
        {name:'cluster_id', type:'string'},
        {name:'cluster_name', type:'string'},
        {name:'rt_id', type:'string'},
        {name:'rt_name', type:'string'},
        {name:'floor_id', type:'string'},
        {name:'area_m2', type:'float'},
        {name:'tax_id', type:'string'},
        {name:'tax_name', type:'string'},
        {name:'qty', type:'float'},
        {name:'price_brutto', type:'float'},
        {name:'voucher_value', type:'float'},
        {name:'price', type:'float'},
        {name:'price_ppn', type:'float'},
        {name:'price_pph', type:'float'},
        {name:'price_sc', type:'float'},
        {name:'total_price', type:'float'},
        {name:'total', type:'float'},
        {name:'advance_value', type:'float'},
        {name:'installment_month', type:'float'},
        {name:'outstanding_month', type:'float'},
        {name:'outstanding_receivable', type:'float'},
        {name:'status', type:'string'},
        {name:'remarks', type:'string'},
        {name:'rs_id', type:'string'},
        {name:'advance_cash_id', type:'string'},
        {name:'cash_name', type:'string'},
        {name:'advance_cflow_id', type:'string'},
        {name:'cflow_name', type:'string'},
        {name:'cust_id', type:'string'},
        {name:'cust_name', type:'string'},
        {name:'start_rent', type:'date'},
        {name:'end_rent', type:'date'},
        {name:'status', type:'string'},
        {name:'co_account', type:'string'},
        {name:'compliment', type:'string'},
        {name:'category', type:'string'},
        {name:'voucher_id', type:'string'},
        {name:'room_service', type:'string'},
        {name:'pax', type:'integer'},
        {name:'doc_type', type:'string'},
        {name:'posted_date', type:'date'},
        {name:'userinput', type:'string'},
        {name:'useredit', type:'string'},
        {name:'timeedit', type:'date'}
    ],
    proxy:{
        type:'direct',
        api:{
            read: Registration_unit_ci.select,
            create: Registration_unit_ci.add,
            update: Registration_unit_ci.update,
            destroy: Registration_unit_ci.delete
        },
        reader :{
            root: 'rows',
            totalProperty: 'totals'
        }
    }
});