
Ext.define('App.model.transactions.marketing.Registration_unit_rent_change', {
	extend: 'Ext.data.Model',
    fields :[
        {name:'co_id', type:'string'},
        {name:'registration_id', type:'integer'},
        {name:'registration_unit_id', type:'integer'},
        {name:'seq_id', type:'integer'},
        {name:'unit_building_id', type:'string'},
        {name:'unit_building_name', type:'string'},
        {name:'building_id', type:'string'},
        {name:'building_name', type:'string'},
        {name:'project_id', type:'string'},
        {name:'project_name', type:'string'},
        {name:'facing_id', type:'string'},
        {name:'facing_name', type:'string'},
        {name:'cluster_id', type:'string'},
        {name:'cluster_name', type:'string'},
        {name:'floor_id', type:'string'},
        {name:'area_m2', type:'float'},
        {name:'qty', type:'float'},
        {name:'price', type:'float'},
        {name:'price_ppn', type:'float'},
        {name:'price_pph', type:'float'},
        {name:'total_price', type:'float'},
        {name:'total', type:'float'},
        {name:'advance_value', type:'float'},
        {name:'installment_month', type:'float'},
        {name:'outstanding_month', type:'float'},
        {name:'tax_id', type:'string'},
        {name:'tax_name', type:'string'},
        {name:'remarks', type:'string'},
        {name:'start_rent', type:'date'},
        {name:'end_rent', type:'date'},

        {name:'unit_building_id_old', type:'string'},
        {name:'unit_building_name_old', type:'string'},
        {name:'building_id_old', type:'string'},
        {name:'building_name_old', type:'string'},
        {name:'project_id_old', type:'string'},
        {name:'project_name_old', type:'string'},
        {name:'facing_id_old', type:'string'},
        {name:'facing_name_old', type:'string'},
        {name:'cluster_id_old', type:'string'},
        {name:'cluster_name_old', type:'string'},
        {name:'floor_id_old', type:'string'},
        {name:'area_m2_old', type:'float'},
        {name:'qty_old', type:'float'},
        {name:'price_old', type:'float'},
        {name:'price_ppn_old', type:'float'},
        {name:'price_pph_old', type:'float'},
        {name:'total_price_old', type:'float'},
        {name:'total_old', type:'float'},
        {name:'advance_value_old', type:'float'},
        {name:'installment_month_old', type:'float'},
        {name:'outstanding_month_old', type:'float'},
        {name:'tax_id_old', type:'string'},
        {name:'tax_name_old', type:'string'},
        {name:'status', type:'string'},
        {name:'remarks_old', type:'string'},
        {name:'start_rent_old', type:'date'},
        {name:'end_rent_old', type:'date'}
    ],
    proxy:{
        type:'direct',
        api:{
            read: Registration_unit_rent_change.select,
            create: Registration_unit_rent_change.add,
            update: Registration_unit_rent_change.update,
            destroy: Registration_unit_rent_change.delete
        },
        reader :{
            root: 'rows',
            totalProperty: 'totals'
        }
    }
});