server {
    listen 80;
    server_name _;
    # Tambahkan baris ini untuk mengizinkan upload hingga 100MB (atau lebih)
    client_max_body_size 100M;

    # Semua request yang masuk ke Nginx akan diteruskan langsung ke Apache
    location / {
        # 'web_php' adalah nama service Apache di docker-compose.yml
        # Port 80 adalah port default Apache di dalam containernya
        proxy_pass http://web_php:80;
        
        # Meneruskan IP asli pengunjung agar terbaca oleh Apache/PHP
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}