
Ext.define('App.model.hris.employee.Employee', {
	extend: 'Ext.data.Model',
    fields :[
        {name:'co_id', type:'string'},
        {name:'doc_id', type:'string'},
        {name:'emp_nik', type:'string'},
        {name:'emp_ktp', type:'string'},
        {name:'emp_id', type:'string'},
        {name:'emp_name', type:'string'},
        {name:'user_id', type:'integer'},
        {name:'afdeling_id', type:'string'},
        {name:'afdeling_name', type:'string'},
        {name:'pks_afdeling', type:'string'},
        {name:'pks_type', type:'string'},
        {name:'attendance_id', type:'integer'},
        {name:'emp_first_name', type:'string'},
        {name:'emp_midle_name', type:'string'},
        {name:'emp_last_name', type:'string'},
        {name:'emp_gender', type:'string'},
        {name:'emp_nation', type:'string'},
        {name:'emp_city', type:'string'},
        {name:'emp_address', type:'string'},
        {name:'emp_zipcode', type:'string'},
        {name:'emp_birth_date', type:'date'},
        {name:'emp_birth_place', type:'string'},
        {name:'emp_marital_status', type:'string'},
        {name:'emp_tlp', type:'string'},
        {name:'emp_email', type:'string'},
        {name:'emp_job_id', type:'string'},
        {name:'emp_job_desc', type:'string'},
        {name:'emp_js_id', type:'string'},
        {name:'emp_js_name', type:'string'},
        {name:'emp_dept_id', type:'string'},
        {name:'emp_dept_name', type:'string'},
        {name:'emp_ol_id', type:'string'},
        {name:'emp_ol_name', type:'string'},
        {name:'emp_company_id', type:'string'},
        {name:'emp_pos_id', type:'string'},
        {name:'emp_join_date', type:'date'},
        {name:'emp_first_date', type:'date'},
        {name:'emp_end_date', type:'date'},
        {name:'emp_salary', type:'float'},
        {name:'emp_ptkp_id', type:'string'},
        {name:'emp_oh_id', type:'string'},
        {name:'emp_npwp', type:'string'},
        {name:'path_image', type:'string'},
        {name:'emp_st_id', type:'string'},
        {name:'emp_st_name', type:'string'},
        {name:'emp_directorate_id', type:'string'},
        {name:'emp_directorate_name', type:'string'},
        {name:'emp_religion', type:'string'},
        {name:'emp_blood', type:'string'},
        {name:'emp_bpjs_kesehatan', type:'string'},
        {name:'emp_bpjs_ketenagakerjaan', type:'string'},
        {name:'emp_bank_01', type:'string'},
        {name:'emp_bank_02', type:'string'},
        {name:'emp_payment_type', type:'string'},
        {name:'emp_group_id', type:'string'},
        {name:'emp_line', type:'string'},
        {name:'emp_overtime', type:'string'},
        {name:'remarks', type:'string'},
        {name:'pph21_show', type:'bool'},
        {name:'active', type:'bool'},
        {name:'userinput', type:'string'},
        {name:'useredit', type:'string'},
        {name:'timeedit', type:'date'}
    ],
    proxy:{
        type:'direct',
        api:{
            read: HRIS_Employee.select,
            create: HRIS_Employee.add,
            update: HRIS_Employee.update,
            destroy: HRIS_Employee.delete
        },
        reader :{
            root: 'rows',
            totalProperty: 'totals'
        }
    }
});