; Mematikan tampilan error di browser
display_errors = Off
display_startup_errors = Off
allow_url_fopen = On
allow_url_include = On

; Menentukan level error yang dilaporkan (mengabaikan warning dan notice)
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE & ~E_WARNING